### ISSUE TITLE
Enum pop

### ISSUE THREAD

**Issue by AtheosCode** [Seneral/Node_Editor#129]
When there are two node, modify one EnumPop first, and then want to change to another node EnumPop, 
 it need twice click to modify otherwise it  will modify the first node, because the focus has not changed。

**Comment by Seneral** [comment]
Yep this is a knoen problem that appears because the standard popup controls eat the click even completely and only let it through AFTER it is closed. That means the nodes are reordered after the selection is made, which confuses the control ID system and assigns the value to the wrong node...
Haven't yet found a solution to that, unfortunately, other than replacing all popup controls...

**Comment by Seneral** [comment]
A matter of #38
